# Generated by Django 4.2.24 on 2026-02-10 10:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("school", "0001_initial"),
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_code",
                    models.CharField(
                        help_text="Assignment code", max_length=50, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Assignment title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Assignment description", null=True
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                            ("participation", "Class Participation"),
                            ("assignment", "Assignment"),
                        ],
                        default="assignment",
                        help_text="Type of assignment/exam",
                        max_length=50,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                            ("participation", "Class Participation"),
                            ("assignment", "Assignment"),
                        ],
                        help_text="Type of assignment/exam (deprecated, use assignment_type)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "full_mark",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full marks for this assignment",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Weight for grading calculation",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(
                        blank=True, help_text="Date assignment was assigned", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Due date and time", null=True
                    ),
                ),
                (
                    "instructions_url",
                    models.URLField(
                        blank=True, default="", help_text="URL to instructions"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of attachment file URLs",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether the assignment is published"
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
                "ordering": ["-due_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this teacher",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="teacher_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Teaching specialization",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("hire_date", models.DateField(help_text="Date of hire")),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("substitute", "Substitute"),
                        ],
                        help_text="Employment status",
                        max_length=50,
                    ),
                ),
                (
                    "highest_degree",
                    models.CharField(
                        blank=True,
                        help_text="Highest educational degree",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        blank=True,
                        help_text="Years of teaching experience",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True,
                        help_text="Office location",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "teachers",
                "ordering": ["user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score/mark received",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum possible score (defaults to assignment.full_mark)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated percentage score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Letter grade (A, B, C, etc.)",
                        max_length=2,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Teacher comments/feedback", null=True
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, help_text="When this was graded", null=True
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this grade is finalized/locked",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment this mark is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="teacher.assignment",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who graded this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_marks",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who received this mark",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mark",
                "verbose_name_plural": "Marks",
                "db_table": "marks",
                "ordering": ["-assignment__due_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Lesson title", max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Detailed lesson content/procedure"),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True, help_text="Learning objectives", null=True
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(
                        blank=True, help_text="Resources/materials needed", null=True
                    ),
                ),
                (
                    "date_planned",
                    models.DateField(
                        help_text="Date when this lesson is planned to be taught"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the lesson plan is visible to others",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this lesson plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="school.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Classroom this lesson plan is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="school.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this lesson plan is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="school.course",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher who created this lesson plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Plan",
                "verbose_name_plural": "Lesson Plans",
                "db_table": "lesson_plans",
                "ordering": ["-date_planned", "title"],
            },
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material_code",
                    models.CharField(
                        help_text="Material code", max_length=50, unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Material title", max_length=150)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Material description", null=True
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        help_text="URL/path to the material file", max_length=255
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="File type/extension",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="school.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Classroom this material is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="school.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this material belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="school.course",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Material",
                "verbose_name_plural": "Learning Materials",
                "db_table": "learning_materials",
                "ordering": ["-academic_year", "course", "title"],
            },
        ),
        migrations.CreateModel(
            name="CourseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academic year for this allocation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_allocations",
                        to="school.academicyear",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        help_text="Classroom where course is taught",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_allocations",
                        to="school.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course being allocated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="school.course",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher assigned to teach this course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_allocations",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Allocation",
                "verbose_name_plural": "Course Allocations",
                "db_table": "course_allocations",
                "ordering": ["course", "class_room"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Attendance date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "course_allocation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course allocation for this attendance",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="teacher.courseallocation",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who recorded this attendance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendances",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student attendance record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "db_table": "attendance",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="course_allocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Course allocation this assignment belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teacher.courseallocation",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                help_text="Teacher who created this assignment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teacher.teacher",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deactivations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["specialization"], name="idx_teachers_specialization"
            ),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(fields=["assignment"], name="idx_marks_assignment"),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.UniqueConstraint(
                fields=("student", "assignment"), name="unique_student_assignment"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonplan",
            index=models.Index(
                fields=["teacher", "date_planned"], name="idx_lesson_plans_teacher_date"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonplan",
            index=models.Index(
                fields=["course", "academic_year"], name="idx_lesson_plans_course_year"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["course", "academic_year"], name="idx_materials_course_year"
            ),
        ),
        migrations.AddIndex(
            model_name="courseallocation",
            index=models.Index(fields=["teacher"], name="idx_allocation_teacher"),
        ),
        migrations.AddIndex(
            model_name="courseallocation",
            index=models.Index(fields=["academic_year"], name="idx_allocation_year"),
        ),
        migrations.AddConstraint(
            model_name="courseallocation",
            constraint=models.UniqueConstraint(
                fields=("course", "class_room", "academic_year"),
                name="unique_course_classroom_year",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="idx_attendance_date"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status"], name="idx_attendance_status"),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "course_allocation", "date"),
                name="unique_student_allocation_date",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["due_date"], name="idx_assignments_due_date"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["is_published"], name="idx_assignments_published"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_date"], name="idx_assignments_assigned"
            ),
        ),
    ]
