# Generated by Django 4.2.24 on 2025-12-28 18:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager", "0002_secretary_remove_workstream_manager_and_more"),
        (
            "accounts",
            "0003_alter_customuser_role_alter_customuser_work_stream_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_code",
                    models.CharField(help_text="Assignment code", max_length=50),
                ),
                (
                    "title",
                    models.CharField(help_text="Assignment title", max_length=150),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Assignment description", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, help_text="Due date", null=True),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                        ],
                        help_text="Type of assignment/exam",
                        max_length=50,
                    ),
                ),
                (
                    "full_mark",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full marks for this assignment",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
                "ordering": ["-due_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this teacher",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="teacher_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Teaching specialization",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("hire_date", models.DateField(help_text="Date of hire")),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("substitute", "Substitute"),
                        ],
                        help_text="Employment status",
                        max_length=50,
                    ),
                ),
                (
                    "highest_degree",
                    models.CharField(
                        blank=True,
                        help_text="Highest educational degree",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        blank=True,
                        help_text="Years of teaching experience",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True,
                        help_text="Office location",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "teachers",
                "ordering": ["user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score/mark received",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment this mark is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="teacher.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who received this mark",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mark",
                "verbose_name_plural": "Marks",
                "db_table": "marks",
                "ordering": ["-assignment__due_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(help_text="Material code", max_length=50),
                ),
                ("title", models.CharField(help_text="Material title", max_length=150)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Material description", null=True
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        help_text="URL/path to the material file", max_length=255
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="manager.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Classroom this material is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="manager.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this material belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="manager.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Material",
                "verbose_name_plural": "Learning Materials",
                "db_table": "learning_materials",
                "ordering": ["-academic_year", "course", "title"],
            },
        ),
        migrations.CreateModel(
            name="CourseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        help_text="Classroom where course is taught",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_allocations",
                        to="manager.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course being allocated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="manager.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher assigned to teach this course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_allocations",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Allocation",
                "verbose_name_plural": "Course Allocations",
                "db_table": "course_allocations",
                "ordering": ["course", "class_room"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Attendance date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        help_text="Classroom for this attendance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="manager.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course for this attendance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="manager.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student attendance record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "db_table": "attendance",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                help_text="Teacher who created this assignment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teacher.teacher",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseallocation",
            constraint=models.UniqueConstraint(
                fields=("course", "class_room", "teacher"),
                name="unique_course_classroom_teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "student"], name="attendance_date_28390b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["course", "date"], name="attendance_course__f6a2dd_idx"
            ),
        ),
    ]
