# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_academicyear_created_at_academicyear_is_active_and_more"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="courseallocation", name="unique_course_classroom_teacher",
        ),
        migrations.RemoveIndex(
            model_name="attendance", name="attendance_date_28390b_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance", name="attendance_course__f6a2dd_idx",
        ),
        migrations.RemoveField(model_name="attendance", name="class_room",),
        migrations.RemoveField(model_name="attendance", name="course",),
        migrations.AddField(
            model_name="assignment",
            name="course_allocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Course allocation this assignment belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teacher.courseallocation",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Whether the assignment is published"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="course_allocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Course allocation for this attendance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="teacher.courseallocation",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher who recorded this attendance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_attendances",
                to="teacher.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic year for this allocation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_allocations",
                to="school.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="file_size",
            field=models.IntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="File type/extension", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mark",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Feedback on the submission", null=True
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="graded_at",
            field=models.DateTimeField(
                blank=True, help_text="When this was graded", null=True
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher who graded this",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_marks",
                to="teacher.teacher",
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_code",
            field=models.CharField(
                help_text="Assignment code", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Due date and time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="learningmaterial",
            name="material_code",
            field=models.CharField(
                help_text="Material code", max_length=50, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["due_date"], name="idx_assignments_due_date"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["is_published"], name="idx_assignments_published"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="idx_attendance_date"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status"], name="idx_attendance_status"),
        ),
        migrations.AddIndex(
            model_name="courseallocation",
            index=models.Index(fields=["teacher"], name="idx_allocation_teacher"),
        ),
        migrations.AddIndex(
            model_name="courseallocation",
            index=models.Index(fields=["academic_year"], name="idx_allocation_year"),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["course", "academic_year"], name="idx_materials_course_year"
            ),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(fields=["assignment"], name="idx_marks_assignment"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["specialization"], name="idx_teachers_specialization"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "course_allocation", "date"),
                name="unique_student_allocation_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseallocation",
            constraint=models.UniqueConstraint(
                fields=("course", "class_room", "academic_year"),
                name="unique_course_classroom_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.UniqueConstraint(
                fields=("student", "assignment"), name="unique_student_assignment"
            ),
        ),
    ]
