# Generated by Django 4.2.24 on 2026-01-21 08:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teacher",
            "0003_assignment_deactivated_at_assignment_deactivated_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assigned_date",
            field=models.DateField(
                blank=True, help_text="Date assignment was assigned", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("homework", "Homework"),
                    ("quiz", "Quiz"),
                    ("midterm", "Midterm Exam"),
                    ("final", "Final Exam"),
                    ("project", "Project"),
                    ("participation", "Class Participation"),
                    ("assignment", "Assignment"),
                ],
                default="assignment",
                help_text="Type of assignment/exam",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="attachments",
            field=models.JSONField(
                blank=True, default=list, help_text="List of attachment file URLs"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructions_url",
            field=models.URLField(
                blank=True, default="", help_text="URL to instructions"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Weight for grading calculation",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="is_final",
            field=models.BooleanField(
                default=False, help_text="Whether this grade is finalized/locked"
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="letter_grade",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Letter grade (A, B, C, etc.)",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="max_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum possible score (defaults to assignment.full_mark)",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated percentage score",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homework", "Homework"),
                    ("quiz", "Quiz"),
                    ("midterm", "Midterm Exam"),
                    ("final", "Final Exam"),
                    ("project", "Project"),
                    ("participation", "Class Participation"),
                    ("assignment", "Assignment"),
                ],
                help_text="Type of assignment/exam (deprecated, use assignment_type)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(help_text="Assignment title", max_length=200),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="courseallocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="courseallocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="learningmaterial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="learningmaterial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mark",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Teacher comments/feedback", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_date"], name="idx_assignments_assigned"
            ),
        ),
    ]
