# Generated by Django 4.2.24 on 2026-01-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_school_academic_year_end_school_academic_year_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "teacher",
            "0004_assignment_assigned_date_assignment_assignment_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Lesson title", max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Detailed lesson content/procedure"),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True, help_text="Learning objectives", null=True
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(
                        blank=True, help_text="Resources/materials needed", null=True
                    ),
                ),
                (
                    "date_planned",
                    models.DateField(
                        help_text="Date when this lesson is planned to be taught"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the lesson plan is visible to others",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this lesson plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="school.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Classroom this lesson plan is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="school.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this lesson plan is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="school.course",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher who created this lesson plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Plan",
                "verbose_name_plural": "Lesson Plans",
                "db_table": "lesson_plans",
                "ordering": ["-date_planned", "title"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "date_planned"],
                        name="idx_lesson_plans_teacher_date",
                    ),
                    models.Index(
                        fields=["course", "academic_year"],
                        name="idx_lesson_plans_course_year",
                    ),
                ],
            },
        ),
    ]
