# Generated by Django 4.2.24 on 2026-01-05 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretary",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this secretary/registrar",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="secretary_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department this secretary belongs to", max_length=100
                    ),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, help_text="Office number", max_length=50, null=True
                    ),
                ),
                ("hire_date", models.DateField(help_text="Date of hire")),
            ],
            options={
                "verbose_name": "Secretary/Registrar",
                "verbose_name_plural": "Secretaries/Registrars",
                "db_table": "secretaries",
                "ordering": ["user__full_name"],
            },
        ),
    ]
