# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretary",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this secretary/registrar",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="secretary_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department this secretary belongs to", max_length=100
                    ),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, help_text="Office number", max_length=50, null=True
                    ),
                ),
                ("hire_date", models.DateField(help_text="Date of hire")),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secretary/Registrar",
                "verbose_name_plural": "Secretaries/Registrars",
                "db_table": "secretaries",
                "ordering": ["user__full_name"],
            },
        ),
    ]
