# Generated by Django 5.2.6 on 2026-01-07 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_code', models.CharField(help_text='Academic year code (e.g., 2025/2026)', max_length=20)),
                ('start_date', models.DateField(help_text='Academic year start date')),
                ('end_date', models.DateField(help_text='Academic year end date')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['-academic_year_code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='Course code', max_length=50)),
                ('name', models.CharField(help_text='Course name', max_length=150)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Grade name (e.g., Grade 1, Kindergarten)', max_length=50)),
                ('numeric_level', models.IntegerField(help_text='Numeric level for ordering', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_age', models.IntegerField(help_text='Minimum age for this grade', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_age', models.IntegerField(help_text='Maximum age for this grade', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['numeric_level'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='School name', max_length=255)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['school_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(help_text='Classroom name', max_length=100)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this classroom', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.academicyear')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'class_rooms',
                'ordering': ['academic_year', 'grade', 'classroom_name'],
            },
        ),
    ]
