# Generated by Django 5.2.8 on 2026-01-29 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(help_text='Course code', max_length=50)),
                ('name', models.CharField(help_text='Course name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Course description', null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Grade name (e.g., Grade 1, Kindergarten)', max_length=50)),
                ('numeric_level', models.IntegerField(help_text='Numeric level for ordering', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_age', models.IntegerField(help_text='Minimum age for this grade', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_age', models.IntegerField(help_text='Maximum age for this grade', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['numeric_level'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, help_text='School location/address', max_length=300, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum number of students', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_email', models.EmailField(blank=True, help_text='School contact email', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='School contact phone', max_length=20, null=True)),
                ('academic_year_start', models.DateField(blank=True, help_text='Academic year start date', null=True)),
                ('academic_year_end', models.DateField(blank=True, help_text='Academic year end date', null=True)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['school_name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year_code', models.CharField(help_text='Academic year code (e.g., 2025/2026)', max_length=20)),
                ('start_date', models.DateField(help_text='Academic year start date')),
                ('end_date', models.DateField(help_text='Academic year end date')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['-academic_year_code'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom_name', models.CharField(help_text='Classroom name', max_length=100)),
                ('capacity', models.IntegerField(blank=True, help_text='Classroom capacity', null=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this classroom', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.academicyear')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'class_rooms',
                'ordering': ['academic_year', 'grade', 'classroom_name'],
            },
        ),
    ]
