# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teacher", "0001_initial"),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Homeroom teacher for this classroom",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classrooms",
                to="teacher.teacher",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                help_text="School this classroom belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deactivations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                help_text="School this academic year belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="school.school",
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["manager"], name="idx_schools_manager"),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_grade_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("numeric_level",), name="unique_numeric_level"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["grade"], name="idx_courses_grade"),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("school", "course_code"), name="unique_school_course_code"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(fields=["grade"], name="idx_classrooms_grade"),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["homeroom_teacher"], name="idx_classrooms_teacher"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "classroom_name"),
                name="unique_school_year_classroom",
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["school", "is_active"], name="idx_academic_years_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year_code"),
                name="unique_school_academic_year_code",
            ),
        ),
    ]
