# Generated by Django 5.2.8 on 2026-01-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('teacher', '0001_initial'),
        ('workstream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, help_text='Homeroom teacher for this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classrooms', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(help_text='Grade level for this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.grade'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(help_text='Grade level for this classroom', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.grade'),
        ),
        migrations.AddField(
            model_name='school',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='work_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='workstream.workstream'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(help_text='School offering this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.school'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(help_text='School this classroom belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.school'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(help_text='School this academic year belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='school.school'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_grade_name'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('numeric_level',), name='unique_numeric_level'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['manager'], name='idx_schools_manager'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['grade'], name='idx_courses_grade'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'course_code'), name='unique_school_course_code'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['grade'], name='idx_classrooms_grade'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['homeroom_teacher'], name='idx_classrooms_teacher'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'classroom_name'), name='unique_school_year_classroom'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'is_active'], name='idx_academic_years_active'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year_code'), name='unique_school_academic_year_code'),
        ),
    ]
