# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_school_options_school_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicyear",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="capacity",
            field=models.IntegerField(
                blank=True, help_text="Classroom capacity", null=True
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, help_text="Course description", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="school",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["school", "is_active"], name="idx_academic_years_active"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(fields=["grade"], name="idx_classrooms_grade"),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["homeroom_teacher"], name="idx_classrooms_teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["grade"], name="idx_courses_grade"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["manager"], name="idx_schools_manager"),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year_code"),
                name="unique_school_academic_year_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("school", "course_code"), name="unique_school_course_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_grade_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("numeric_level",), name="unique_numeric_level"
            ),
        ),
    ]
