# Generated by Django 4.2.24 on 2026-01-21 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_academicyear_deactivated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="academic_year_end",
            field=models.DateField(
                blank=True, help_text="Academic year end date", null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="academic_year_start",
            field=models.DateField(
                blank=True, help_text="Academic year start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of students",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_email",
            field=models.EmailField(
                blank=True, help_text="School contact email", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="School contact phone", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="School location/address",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
