# Generated by Django 5.2.8 on 2025-12-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Email address used for login', max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=150)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('register', 'Registrar/Secretary'), ('manager_school', 'School Manager'), ('manager_workstream', 'Workstream Manager'), ('guardian', 'Guardian'), ('admin', 'Admin')], db_index=True, help_text='User role', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, help_text='School this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='manager.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('work_stream', models.ForeignKey(blank=True, help_text='Workstream this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='manager.workstream')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
        ),
    ]
