# Generated by Django 5.2.6 on 2026-01-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(help_text='Configuration key', max_length=100)),
                ('config_value', models.TextField(help_text='Configuration value')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configurations',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Email address used for login', max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=150)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('secretary', 'Secretary'), ('manager_school', 'School Manager'), ('manager_workstream', 'Workstream Manager'), ('guardian', 'Guardian'), ('admin', 'Admin'), ('guest', 'Guest')], db_index=True, default='guest', help_text='User role', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
    ]
