# Generated by Django 5.2.6 on 2026-01-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school', '0002_initial'),
        ('workstream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='school.school'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_stream',
            field=models.ForeignKey(blank=True, help_text='Workstream this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workstream.workstream'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School-specific config (null for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='school.school'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['school', 'config_key'], name='system_conf_school__7a2560_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemconfiguration',
            constraint=models.UniqueConstraint(fields=('school', 'config_key'), name='unique_school_config_key'),
        ),
    ]
