# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0002_initial"),
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("workstream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School-specific config (null for global/workstream-specific)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="work_stream",
            field=models.ForeignKey(
                blank=True,
                help_text="Workstream-specific config (null for global/school-specific)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="workstream.workstream",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deactivations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="work_stream",
            field=models.ForeignKey(
                blank=True,
                help_text="Workstream this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="workstream.workstream",
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfiguration",
            index=models.Index(
                fields=["school", "config_key"], name="idx_sys_config_school"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfiguration",
            index=models.Index(
                fields=["work_stream", "config_key"], name="idx_sys_config_workstream"
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", True)),
                fields=("work_stream", "config_key"),
                name="unique_workstream_config_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.UniqueConstraint(
                fields=("school", "config_key"), name="unique_school_config_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("school__isnull", True), ("work_stream__isnull", True)
                ),
                fields=("config_key",),
                name="unique_global_config_key",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="idx_users_email"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="idx_users_role"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["work_stream"], name="idx_users_work_stream"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["school"], name="idx_users_school"),
        ),
    ]
