# Generated by Django 5.2.8 on 2025-12-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="manager.school",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="work_stream",
            field=models.ForeignKey(
                blank=True,
                help_text="Workstream this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="manager.workstream",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("register", "Registrar/Secretary"),
                    ("manager_school", "School Manager"),
                    ("manager_workstream", "Workstream Manager"),
                    ("guardian", "Guardian"),
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                ],
                db_index=True,
                default="guest",
                help_text="User role",
                max_length=50,
            ),
        ),
    ]
