# Generated by Django 5.2.8 on 2025-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('register', 'Registrar/Secretary'), ('manager_school', 'School Manager'), ('manager_workstream', 'Workstream Manager'), ('guardian', 'Guardian'), ('admin', 'Admin')], db_index=True, default='student', help_text='User role', max_length=50),
        ),
    ]
