# Generated by Django 4.2.24 on 2026-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_notifications",
            field=models.BooleanField(
                default=True, help_text="Whether email notifications are enabled"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="enable_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Whether two-factor authentication preference is enabled",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="in_app_alerts",
            field=models.BooleanField(
                default=True, help_text="Whether in-app alerts are enabled"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sms_notifications",
            field=models.BooleanField(
                default=False, help_text="Whether SMS notifications are enabled"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Preferred timezone for this user",
                max_length=64,
            ),
        ),
    ]
