# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="systemconfiguration",
            new_name="idx_sys_config_lookup",
            old_name="system_conf_school__7a2560_idx",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="idx_users_email"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="idx_users_role"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["work_stream"], name="idx_users_work_stream"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["school"], name="idx_users_school"),
        ),
    ]
