# Generated by Django 5.2.8 on 2025-12-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_school_customuser_work_stream_and_more"),
        ("manager", "0001_initial"),
        ("workstream", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("secretary", "Secretary"),
                    ("manager_school", "School Manager"),
                    ("manager_workstream", "Workstream Manager"),
                    ("guardian", "Guardian"),
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                ],
                db_index=True,
                default="student",
                help_text="User role",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="work_stream",
            field=models.ForeignKey(
                blank=True,
                help_text="Workstream this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="workstream.workstream",
            ),
        ),
        migrations.AlterModelTable(name="customuser", table="users",),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(help_text="Configuration key", max_length=100),
                ),
                ("config_value", models.TextField(help_text="Configuration value")),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School-specific config (null for global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="manager.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "system_configurations",
                "indexes": [
                    models.Index(
                        fields=["school", "config_key"],
                        name="system_conf_school__7a2560_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "config_key"), name="unique_school_config_key"
                    )
                ],
            },
        ),
    ]
