# Generated by Django 5.2.8 on 2025-12-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_customuser_role_alter_customuser_work_stream_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("secretary", "Secretary"),
                    ("manager_school", "School Manager"),
                    ("manager_workstream", "Workstream Manager"),
                    ("guardian", "Guardian"),
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                ],
                db_index=True,
                default="guest",
                help_text="User role",
                max_length=50,
            ),
        ),
    ]
