# Generated by Codex on 2026-02-15

from django.db import migrations


def _sanitize_identifier(value, fallback):
    cleaned = "".join(ch for ch in str(value or "") if ch.isalnum() or ch == "_")
    return cleaned or fallback


def _get_mysql_indexes(cursor):
    cursor.execute("SHOW INDEX FROM `users`")
    rows = cursor.fetchall()
    if not rows:
        return []

    columns = [column[0] for column in cursor.description]
    return [dict(zip(columns, row)) for row in rows]


def _drop_email_unique_indexes(cursor):
    unique_index_names = []
    for index in _get_mysql_indexes(cursor):
        key_name = index.get("Key_name")
        non_unique = int(index.get("Non_unique", 1))
        column_name = index.get("Column_name")

        if key_name == "PRIMARY" or non_unique != 0 or column_name != "email":
            continue

        if key_name not in unique_index_names:
            unique_index_names.append(key_name)

    for index_name in unique_index_names:
        cursor.execute(f"ALTER TABLE `users` DROP INDEX `{index_name}`")

    return unique_index_names


def _add_email_unique_indexes(cursor, index_names):
    if not index_names:
        index_names = ["uniq_users_email"]

    existing_names = {index.get("Key_name") for index in _get_mysql_indexes(cursor)}
    for index_name in index_names:
        if index_name in existing_names:
            continue
        cursor.execute(f"ALTER TABLE `users` ADD UNIQUE INDEX `{index_name}` (`email`)")


def apply_case_sensitive_email_collation(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        unique_indexes = _drop_email_unique_indexes(cursor)
        cursor.execute(
            "ALTER TABLE `users` "
            "MODIFY `email` VARCHAR(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL"
        )
        _add_email_unique_indexes(cursor, unique_indexes)


def revert_case_sensitive_email_collation(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        unique_indexes = _drop_email_unique_indexes(cursor)
        cursor.execute("SELECT @@character_set_database, @@collation_database")
        row = cursor.fetchone() or ("utf8mb4", "utf8mb4_unicode_ci")
        charset = _sanitize_identifier(row[0], "utf8mb4")
        collation = _sanitize_identifier(row[1], "utf8mb4_unicode_ci")

        cursor.execute(
            "ALTER TABLE `users` "
            f"MODIFY `email` VARCHAR(254) CHARACTER SET {charset} COLLATE {collation} NOT NULL"
        )
        _add_email_unique_indexes(cursor, unique_indexes)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_settings_preferences"),
    ]

    operations = [
        migrations.RunPython(
            apply_case_sensitive_email_collation,
            revert_case_sensitive_email_collation,
        ),
    ]
