# Generated by Django 4.2.24 on 2026-01-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_school_academic_year_end_school_academic_year_start_and_more"),
        ("workstream", "0005_alter_workstream_options_and_more"),
        ("accounts", "0006_customuser_created_by_alter_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="systemconfiguration",
            new_name="idx_sys_config_school",
            old_name="idx_sys_config_lookup",
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="work_stream",
            field=models.ForeignKey(
                blank=True,
                help_text="Workstream-specific config (null for global/school-specific)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="workstream.workstream",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School-specific config (null for global/workstream-specific)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="school.school",
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfiguration",
            index=models.Index(
                fields=["work_stream", "config_key"], name="idx_sys_config_workstream"
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", True)),
                fields=("work_stream", "config_key"),
                name="unique_workstream_config_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("school__isnull", True), ("work_stream__isnull", True)
                ),
                fields=("config_key",),
                name="unique_global_config_key",
            ),
        ),
    ]
