# Generated by Django 4.2.24 on 2026-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_rename_idx_sys_config_lookup_idx_sys_config_school_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="feaid",
            field=models.CharField(
                blank=True, help_text="FEA ID", max_length=50, null=True
            ),
        ),
    ]
