import requests
from requests.auth import HTTPBasicAuth

BASE_URL = "http://localhost:8000"
LOGIN_URL = f"{BASE_URL}/api/token/"
ASSIGNMENTS_URL = f"{BASE_URL}/api/teacher/assignments/"
TIMEOUT = 30

USERNAME = "g@gh.com"
PASSWORD = "1"


def get_jwt_token(username, password):
    # Since PRD states JWT auth but test credentials are basic username/password,
    # assume API provides a token endpoint to get JWT token via Basic Auth or credential post.
    # For this test, we simulate getting JWT by posting credentials to an auth endpoint.
    # However, no token URL given, so use Basic Auth to get token from /api/token/ (common pattern)
    # If missing, attempt direct Basic Auth usage.
    # Here we try POST /api/token/ with username/password to get JWT tokens.

    payload = {"username": username, "password": password}
    # Common JWT auth token endpoint pattern
    url = f"{BASE_URL}/api/token/"
    try:
        resp = requests.post(url, json=payload, timeout=TIMEOUT)
        resp.raise_for_status()
        tokens = resp.json()
        access = tokens.get("access")
        if not access:
            raise ValueError("No access token received")
        return access
    except Exception:
        # fallback: try Basic Auth to hit a protected endpoint to get JWT from response if possible
        raise


def create_assignment(auth_header, data):
    resp = requests.post(
        ASSIGNMENTS_URL,
        headers=auth_header,
        json=data,
        timeout=TIMEOUT
    )
    return resp


def delete_assignment(auth_header, assignment_id):
    url = f"{ASSIGNMENTS_URL}{assignment_id}/"
    resp = requests.delete(url, headers=auth_header, timeout=TIMEOUT)
    return resp


def test_create_assignment_with_autogenerated_code():
    # Get JWT token
    token = get_jwt_token(USERNAME, PASSWORD)
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }

    # Prepare valid assignment data without assignment_code to test auto-generation
    assignment_data = {
        "title": "Sample Assignment Title TC002",
        "exam_type": "assignment",
        "full_mark": 100,
        "description": "This is a test assignment created without assignment_code to verify auto-generation.",
        "due_date": "2026-12-31"
    }

    assignment_id = None

    try:
        # Create assignment without assignment_code
        response = create_assignment(headers, assignment_data)
        # Validate response status 201 Created
        assert response.status_code == 201, f"Expected 201, got {response.status_code}"
        data = response.json()

        # Validate required fields exist in response and assignment_code is auto-generated
        assert "id" in data and isinstance(data["id"], int), "Missing or invalid assignment id"
        assert "assignment_code" in data and isinstance(data["assignment_code"], str) and data["assignment_code"], \
            "assignment_code should be auto-generated and not empty"
        assert data["title"] == assignment_data["title"], "Title mismatch"
        assert data["exam_type"] == assignment_data["exam_type"], "exam_type mismatch"
        assert isinstance(data["full_mark"], str), "full_mark should be string in response"
        assignment_id = data["id"]

        # Additional validation: attempt to create with missing required fields to ensure validation error 400
        invalid_data_missing_title = {
            "exam_type": "quiz",
            "full_mark": 20
        }
        invalid_resp = create_assignment(headers, invalid_data_missing_title)
        assert invalid_resp.status_code == 400, f"Expected 400 for missing title, got {invalid_resp.status_code}"

        # Additional validation: invalid enum for exam_type causes 400
        invalid_data_bad_enum = {
            "title": "Invalid Exam Type",
            "exam_type": "invalid_exam_type",
            "full_mark": 50
        }
        invalid_enum_resp = create_assignment(headers, invalid_data_bad_enum)
        assert invalid_enum_resp.status_code == 400, f"Expected 400 for invalid exam_type, got {invalid_enum_resp.status_code}"

    finally:
        # Clean up by deleting the created assignment if it exists
        if assignment_id:
            del_resp = delete_assignment(headers, assignment_id)
            # Accept 204 No Content or 404 Not Found if already deleted
            assert del_resp.status_code in (204, 404), f"Failed to delete assignment id {assignment_id}"



test_create_assignment_with_autogenerated_code()