# Generated by Django 5.2.8 on 2026-01-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('other', 'Other')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(help_text='Type of object affected (e.g. School, User)', max_length=50)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the affected object', max_length=50, null=True)),
                ('description', models.TextField(help_text='Human readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='idx_activity_action'), models.Index(fields=['actor'], name='idx_activity_actor'), models.Index(fields=['created_at'], name='idx_activity_created')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Client info', null=True)),
                ('user', models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login History',
                'verbose_name_plural': 'User Login Histories',
                'db_table': 'user_login_history',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='idx_login_user_time'), models.Index(fields=['login_time'], name='idx_login_time')],
            },
        ),
    ]
