# Generated by Django 5.2.6 on 2026-01-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(help_text='User account for this student', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(help_text='Student date of birth')),
                ('admission_date', models.DateField(help_text='Date of admission')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='active', help_text='Current enrollment status', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Student address', null=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Medical information/notes', null=True)),
                ('grade', models.ForeignKey(blank=True, help_text='Current grade level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.grade')),
                ('school', models.ForeignKey(help_text='School this student belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred')], help_text='Enrollment status', max_length=20, null=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.academicyear')),
                ('class_room', models.ForeignKey(help_text='Classroom student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.classroom')),
                ('student', models.ForeignKey(help_text='Enrolled student', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'db_table': 'student_enrollments',
                'ordering': ['academic_year', 'class_room', 'student'],
                'constraints': [models.UniqueConstraint(fields=('student', 'class_room'), name='unique_student_classroom')],
            },
        ),
    ]
