# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this student",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="Student ID number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("date_of_birth", models.DateField(help_text="Student date of birth")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        help_text="Student gender",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Current grade level (integer fallback)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("admission_date", models.DateField(help_text="Date of admission")),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending"),
                            ("expelled", "Expelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        help_text="Current enrollment status",
                        max_length=50,
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending"),
                            ("expelled", "Expelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        help_text="Current enrollment status (deprecated, use enrollment_status)",
                        max_length=50,
                    ),
                ),
                (
                    "current_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current GPA",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "total_absences",
                    models.IntegerField(default=0, help_text="Total absences count"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Student address", null=True
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="National ID number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact info",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(
                        blank=True, help_text="Medical information/notes", null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Student phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current grade level",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="school.grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
                "ordering": ["user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        help_text="Enrollment status",
                        max_length=20,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        blank=True, help_text="Date of enrollment", null=True
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, help_text="Date of completion", null=True
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this enrollment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="school.academicyear",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        help_text="Classroom student is enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="school.classroom",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Enrolled student",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "db_table": "student_enrollments",
                "ordering": ["academic_year", "class_room", "student"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_enrollment_status"),
                    models.Index(fields=["academic_year"], name="idx_enrollment_year"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="studentenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_room", "academic_year"),
                name="unique_student_classroom_year",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_status"], name="idx_students_enrollment_status"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["date_of_birth"], name="idx_students_dob"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["student_id"], name="idx_students_student_id"),
        ),
    ]
