# Generated by Django 4.2.24 on 2026-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Student phone number", max_length=20, null=True
            ),
        ),
    ]
