# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentenrollment", name="unique_student_classroom",
        ),
        migrations.RemoveField(model_name="student", name="grade",),
        migrations.RemoveField(model_name="student", name="school",),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="completion_date",
            field=models.DateField(
                blank=True, help_text="Date of completion", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="enrollment_date",
            field=models.DateField(
                blank=True, help_text="Date of enrollment", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("enrolled", "Enrolled"),
                    ("completed", "Completed"),
                    ("withdrawn", "Withdrawn"),
                    ("transferred", "Transferred"),
                ],
                default="active",
                help_text="Enrollment status",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["current_status"], name="idx_students_status"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["date_of_birth"], name="idx_students_dob"),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(fields=["status"], name="idx_enrollment_status"),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(fields=["academic_year"], name="idx_enrollment_year"),
        ),
        migrations.AddConstraint(
            model_name="studentenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_room", "academic_year"),
                name="unique_student_classroom_year",
            ),
        ),
    ]
