# Generated by Django 5.2.8 on 2026-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('expelled', 'Expelled'), ('rejected', 'Rejected')], default='active', help_text='Current enrollment status (deprecated, use enrollment_status)', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('expelled', 'Expelled'), ('rejected', 'Rejected')], default='active', help_text='Current enrollment status', max_length=50),
        ),
    ]
