# Generated by Django 4.2.24 on 2026-01-21 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_student_deactivated_at_student_deactivated_by_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="student", name="idx_students_status",),
        migrations.AddField(
            model_name="student",
            name="current_gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current GPA",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact info",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="active",
                help_text="Current enrollment status",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                help_text="Student gender",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grade_level",
            field=models.IntegerField(
                blank=True,
                help_text="Current grade level",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="national_id",
            field=models.CharField(
                blank=True, help_text="National ID number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="Student ID number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="total_absences",
            field=models.IntegerField(default=0, help_text="Total absences count"),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="active",
                help_text="Current enrollment status (deprecated, use enrollment_status)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_status"], name="idx_students_enrollment_status"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["student_id"], name="idx_students_student_id"),
        ),
    ]
