# Generated by Django 4.2.24 on 2026-01-21 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_school_academic_year_end_school_academic_year_start_and_more"),
        ("student", "0004_remove_student_idx_students_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                help_text="Current grade level",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="school.grade",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_level",
            field=models.IntegerField(
                blank=True,
                help_text="Current grade level (integer fallback)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
