# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Message subject",
                        max_length=200,
                    ),
                ),
                ("body", models.TextField(help_text="Message body/content")),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, help_text="List of attachment URLs"
                    ),
                ),
                (
                    "thread_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Thread identifier for grouping messages",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the message was sent"
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False, help_text="Whether this is a draft message"
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent message if this is a reply",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="user_messages.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When the message was read", null=True
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recipient deleted this message",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="user_messages.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The recipient",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Receipt",
                "verbose_name_plural": "Message Receipts",
                "db_table": "message_receipts",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Users who received the message",
                related_name="received_messages",
                through="user_messages.MessageReceipt",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="User who sent the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="messagereceipt",
            index=models.Index(
                fields=["recipient", "is_read"], name="idx_receipt_recipient_read"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereceipt", unique_together={("message", "recipient")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread_id", "sent_at"], name="idx_messages_thread"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "sent_at"], name="idx_messages_sender_sent"
            ),
        ),
    ]
