# Generated by Django 5.2.8 on 2026-02-14 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(help_text='Users who received the message', related_name='received_messages', through='user_messages.MessageReceipt', through_fields=('message', 'recipient'), to=settings.AUTH_USER_MODEL),
        ),
    ]
