# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="idx_messages_receiver_read",
            old_name="messages_receive_c45f39_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="idx_messages_sender_sent",
            old_name="messages_sender__039ac4_idx",
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
