# Generated by Django 4.2.24 on 2026-01-21 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "user_messages",
            "0003_message_deactivated_at_message_deactivated_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When the message was read", null=True
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recipient deleted this message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Receipt",
                "verbose_name_plural": "Message Receipts",
                "db_table": "message_receipts",
            },
        ),
        migrations.RemoveIndex(
            model_name="message", name="idx_messages_receiver_read",
        ),
        migrations.RemoveField(model_name="message", name="is_read",),
        migrations.RemoveField(model_name="message", name="read_at",),
        migrations.RemoveField(model_name="message", name="receiver",),
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.JSONField(
                blank=True, default=list, help_text="List of attachment URLs"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_draft",
            field=models.BooleanField(
                default=False, help_text="Whether this is a draft message"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="user_messages.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                help_text="Thread identifier for grouping messages",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                blank=True, default="", help_text="Message subject", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread_id", "sent_at"], name="idx_messages_thread"
            ),
        ),
        migrations.AddField(
            model_name="messagereceipt",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deactivations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagereceipt",
            name="message",
            field=models.ForeignKey(
                help_text="The message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="user_messages.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereceipt",
            name="recipient",
            field=models.ForeignKey(
                help_text="The recipient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Users who received the message",
                related_name="received_messages",
                through="user_messages.MessageReceipt",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="messagereceipt",
            index=models.Index(
                fields=["recipient", "is_read"], name="idx_receipt_recipient_read"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereceipt", unique_together={("message", "recipient")},
        ),
    ]
