# Generated by Django 5.2.8 on 2026-01-29 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workstream_name', models.CharField(help_text='Workstream name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Workstream description', null=True)),
                ('capacity', models.IntegerField(help_text='Maximum number of schools', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, help_text='Workstream regional location', max_length=255, null=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager of this workstream', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workstreams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workstream',
                'verbose_name_plural': 'Workstreams',
                'db_table': 'work_streams',
                'ordering': ['workstream_name'],
                'indexes': [models.Index(fields=['manager'], name='idx_work_streams_manager')],
            },
        ),
    ]
