# Generated by Django 5.2.8 on 2025-12-28 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Workstream name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Workstream description", null=True
                    ),
                ),
                (
                    "max_user",
                    models.IntegerField(
                        help_text="Maximum number of users",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this workstream is active"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Manager of this workstream",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_workstreams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workstream",
                "verbose_name_plural": "Workstreams",
                "db_table": "work_streams",
                "ordering": ["name"],
            },
        ),
    ]
