# Generated by Django 4.2.24 on 2026-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstream",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Workstream URL slug",
                max_length=255,
                null=True,
            ),
        ),
    ]
