# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workstream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstream",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workstream",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="workstream",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager of this workstream",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_workstreams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="workstream",
            index=models.Index(fields=["manager"], name="idx_work_streams_manager"),
        ),
    ]
