# Generated by Django 5.2.8 on 2026-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstream', '0002_workstream_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstream',
            name='slug',
            field=models.SlugField(blank=True, help_text='Workstream URL slug', max_length=255, null=True, unique=True),
        ),
    ]
