# Generated by Django 4.2.24 on 2026-01-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workstream", "0002_workstream_created_at_workstream_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstream",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workstream",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deactivations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workstream",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
