# Generated by Django 4.2.24 on 2026-01-19 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstream",
            "0003_workstream_deactivated_at_workstream_deactivated_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workstream",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workstream",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
