# Generated by Django 4.2.24 on 2026-01-21 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstream", "0004_alter_workstream_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workstream",
            options={
                "ordering": ["workstream_name"],
                "verbose_name": "Workstream",
                "verbose_name_plural": "Workstreams",
            },
        ),
        migrations.RenameField(
            model_name="workstream", old_name="name", new_name="workstream_name",
        ),
        migrations.RemoveField(model_name="workstream", name="max_user",),
        migrations.AddField(
            model_name="workstream",
            name="capacity",
            field=models.IntegerField(
                default=100,
                help_text="Maximum number of schools",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workstream",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="workstream",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
