# Generated by Django 4.2.24 on 2026-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstream", "0005_alter_workstream_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstream",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Workstream regional location",
                max_length=255,
                null=True,
            ),
        ),
    ]
