# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification body/content")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("grade_posted", "Grade Posted"),
                            ("assignment_due", "Assignment Due Soon"),
                            ("attendance_marked", "Attendance Marked"),
                            ("announcement", "Announcement"),
                            ("message_received", "Message Received"),
                            ("account_change", "Account Change"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL for action",
                        max_length=500,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of related object",
                        max_length=50,
                    ),
                ),
                (
                    "related_object_id",
                    models.IntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, help_text="Whether email notification was sent"
                    ),
                ),
                (
                    "push_sent",
                    models.BooleanField(
                        default=False, help_text="Whether push notification was sent"
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Workstream", "Workstream"),
                            ("School", "School"),
                            ("User", "User"),
                        ],
                        db_index=True,
                        help_text="Scope type for this notification (legacy)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "scope_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the scope entity (legacy)",
                        null=True,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="User receiving this notification",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this notification",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="idx_notifications_recipient",
                    ),
                    models.Index(
                        fields=["scope_type", "scope_id"],
                        name="idx_notifications_scope",
                    ),
                    models.Index(
                        fields=["created_at"], name="idx_notifications_created"
                    ),
                ],
            },
        ),
    ]
