# Generated by Django 4.2.24 on 2025-12-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("Workstream", "Workstream"),
                            ("School", "School"),
                            ("User", "User"),
                        ],
                        db_index=True,
                        help_text="Scope type for this notification",
                        max_length=20,
                    ),
                ),
                (
                    "scope_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="ID of the scope entity (workstream, school, or user)",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=150),
                ),
                ("body", models.TextField(help_text="Notification body/content")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notification was created"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who created this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope_type", "scope_id"],
                        name="notificatio_scope_t_511b8a_idx",
                    )
                ],
            },
        ),
    ]
