# Generated by Django 4.2.24 on 2026-01-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="idx_notifications_scope",
            old_name="notificatio_scope_t_511b8a_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="idx_notifications_created"),
        ),
    ]
