# Generated by Django 4.2.24 on 2026-01-21 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_notification_deactivated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="body", new_name="message",
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True, default="", help_text="URL for action", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(
                default=False, help_text="Whether email notification was sent"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Whether the notification has been read"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("grade_posted", "Grade Posted"),
                    ("assignment_due", "Assignment Due Soon"),
                    ("attendance_marked", "Attendance Marked"),
                    ("announcement", "Announcement"),
                    ("message_received", "Message Received"),
                    ("account_change", "Account Change"),
                    ("system", "System Notification"),
                ],
                default="system",
                help_text="Type of notification",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="push_sent",
            field=models.BooleanField(
                default=False, help_text="Whether push notification was sent"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="When the notification was read", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="User receiving this notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_id",
            field=models.IntegerField(
                blank=True, help_text="ID of related object", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of related object",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="scope_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the scope entity (legacy)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="scope_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Workstream", "Workstream"),
                    ("School", "School"),
                    ("User", "User"),
                ],
                db_index=True,
                help_text="Scope type for this notification (legacy)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(help_text="Notification title", max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "created_at"],
                name="idx_notifications_recipient",
            ),
        ),
    ]
