# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this guardian",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="guardian_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Guardian phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
                "db_table": "guardians",
                "ordering": ["user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="GuardianStudentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("legal_guardian", "Legal Guardian"),
                            ("foster_parent", "Foster Parent"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        help_text="Type of relationship",
                        max_length=50,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary guardian?"
                    ),
                ),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True, help_text="Can this guardian pick up the student?"
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        help_text="Guardian in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="guardian.guardian",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian Student Link",
                "verbose_name_plural": "Guardian Student Links",
                "db_table": "guardian_student_link",
                "ordering": ["guardian", "student"],
            },
        ),
    ]
