# Generated by Django 4.2.24 on 2025-12-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0001_initial"),
        (
            "accounts",
            "0003_alter_customuser_role_alter_customuser_work_stream_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this guardian",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="guardian_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Guardian phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
                "db_table": "guardians",
                "ordering": ["user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="GuardianStudentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        help_text="Type of relationship",
                        max_length=50,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        help_text="Guardian in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="guardian.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian Student Link",
                "verbose_name_plural": "Guardian Student Links",
                "db_table": "guardian_student_link",
                "ordering": ["guardian", "student"],
            },
        ),
        migrations.AddConstraint(
            model_name="guardianstudentlink",
            constraint=models.UniqueConstraint(
                fields=("guardian", "student"), name="unique_guardian_student"
            ),
        ),
    ]
