# Generated by Django 5.2.6 on 2026-01-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('user', models.OneToOneField(help_text='User account for this guardian', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guardian_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, help_text='Guardian phone number', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'guardians',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='GuardianStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], help_text='Type of relationship', max_length=50)),
                ('guardian', models.ForeignKey(help_text='Guardian in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='guardian.guardian')),
            ],
            options={
                'verbose_name': 'Guardian Student Link',
                'verbose_name_plural': 'Guardian Student Links',
                'db_table': 'guardian_student_link',
                'ordering': ['guardian', 'student'],
            },
        ),
    ]
