# Generated by Django 5.2.6 on 2026-01-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardian', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudentlink',
            name='student',
            field=models.ForeignKey(help_text='Student in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='student.student'),
        ),
        migrations.AddConstraint(
            model_name='guardianstudentlink',
            constraint=models.UniqueConstraint(fields=('guardian', 'student'), name='unique_guardian_student'),
        ),
    ]
