# Generated by Django 5.2.8 on 2026-01-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardian', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudentlink',
            name='student',
            field=models.BigIntegerField(help_text='Student ID in this relationship', null=True),
        ),
        # migrations.AddIndex(
        #     model_name='guardianstudentlink',
        #     index=models.Index(fields=['student'], name='idx_link_student'),
        # ),
        # migrations.AddConstraint(
        #     model_name='guardianstudentlink',
        #     constraint=models.UniqueConstraint(fields=('guardian', 'student'), name='unique_guardian_student'),
        # ),
    ]
