# Generated by Django 5.2.8 on 2026-02-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0003_fix_student_fk'),
        ('student', '0003_alter_student_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianstudentlink',
            name='student',
            field=models.ForeignKey(help_text='Student in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='student.student'),
        ),
    ]
