# Generated by Django 4.2.24 on 2026-01-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0004_guardian_deactivated_at_guardian_deactivated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianstudentlink",
            name="can_pickup",
            field=models.BooleanField(
                default=True, help_text="Can this guardian pick up the student?"
            ),
        ),
        migrations.AddField(
            model_name="guardianstudentlink",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Is this the primary guardian?"
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="guardianstudentlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="guardianstudentlink",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("legal_guardian", "Legal Guardian"),
                    ("foster_parent", "Foster Parent"),
                    ("sibling", "Sibling"),
                    ("other", "Other"),
                ],
                help_text="Type of relationship",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="guardianstudentlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
