# Generated by Django 4.2.24 on 2026-02-10 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("evaluation_date", models.DateField(help_text="Date of evaluation")),
                (
                    "rating_score",
                    models.IntegerField(
                        help_text="Rating score",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Evaluation comments", null=True
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deactivations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewee",
                    models.ForeignKey(
                        help_text="User being evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewee_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="User who performed the evaluation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Evaluation",
                "verbose_name_plural": "Staff Evaluations",
                "db_table": "staff_evaluations",
                "ordering": ["-evaluation_date"],
            },
        ),
    ]
