# Generated by Django 4.2.24 on 2025-12-18 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Grade name (e.g., Grade 1, Kindergarten)",
                        max_length=50,
                    ),
                ),
                (
                    "numeric_level",
                    models.IntegerField(
                        help_text="Numeric level for ordering",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_age",
                    models.IntegerField(
                        help_text="Minimum age for this grade",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_age",
                    models.IntegerField(
                        help_text="Maximum age for this grade",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "db_table": "grade",
                "ordering": ["numeric_level"],
            },
        ),
        migrations.CreateModel(
            name="WorkStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Workstream name", max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "max_user",
                    models.IntegerField(
                        help_text="Maximum number of users",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this workstream is active"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Manager of this workstream",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_workstreams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workstream",
                "verbose_name_plural": "Workstreams",
                "db_table": "workstream",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateField(help_text="Date of evaluation")),
                (
                    "rating_score",
                    models.IntegerField(
                        help_text="Rating score",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Evaluation comments", null=True
                    ),
                ),
                (
                    "reviewee",
                    models.ForeignKey(
                        help_text="User being evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewee_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="User who performed the evaluation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Evaluation",
                "verbose_name_plural": "Staff Evaluations",
                "db_table": "staff_evaluation",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        help_text="School name", max_length=100, unique=True
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="School manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_schools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_stream",
                    models.ForeignKey(
                        help_text="Workstream this school belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="manager.workstream",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "school",
                "ordering": ["school_name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year_code",
                    models.CharField(
                        db_index=True,
                        help_text="Academic year code (e.g., 2024-2025)",
                        max_length=9,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Academic year start date")),
                ("end_date", models.DateField(help_text="Academic year end date")),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School this academic year belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="manager.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "db_table": "academic_year",
                "ordering": ["-academic_year_code"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(help_text="Configuration key", max_length=100),
                ),
                ("config_value", models.TextField(help_text="Configuration value")),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School-specific config (null for global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="manager.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "system_configuration",
                "indexes": [
                    models.Index(
                        fields=["school", "config_key"],
                        name="system_conf_school__2e2d3e_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.UniqueConstraint(
                fields=("school", "config_key"), name="unique_school_config_key"
            ),
        ),
    ]
