# Generated by Django 5.2.8 on 2025-12-04 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workstream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of students / classes this workstream can handle."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this workstream.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workstreams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        help_text="User account for the manager of this workstream.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_workstream",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall performance score (e.g. 0–10).",
                        max_digits=4,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workstream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="manager.workstream",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="DepartmentActivityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily student attendance rate (0–100).",
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workstream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_reports",
                        to="manager.workstream",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("workstream", "date")},
            },
        ),
    ]
