# Generated by Django 5.2.8 on 2025-12-28 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_customuser_role_alter_customuser_work_stream_and_more",
        ),
        ("manager", "0001_initial"),
        ("workstream", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretary",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this secretary/registrar",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="secretary_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department this secretary belongs to", max_length=100
                    ),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, help_text="Office number", max_length=50, null=True
                    ),
                ),
                ("hire_date", models.DateField(help_text="Date of hire")),
            ],
            options={
                "verbose_name": "Secretary/Registrar",
                "verbose_name_plural": "Secretaries/Registrars",
                "db_table": "secretaries",
                "ordering": ["user__full_name"],
            },
        ),
        migrations.RemoveField(model_name="workstream", name="manager",),
        migrations.AlterField(
            model_name="school",
            name="work_stream",
            field=models.ForeignKey(
                help_text="Workstream this school belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schools",
                to="workstream.workstream",
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="academic_year_code",
            field=models.CharField(
                help_text="Academic year code (e.g., 2025/2026)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_name",
            field=models.CharField(help_text="School name", max_length=255),
        ),
        migrations.AlterModelTable(name="academicyear", table="academic_years",),
        migrations.AlterModelTable(name="grade", table="grades",),
        migrations.AlterModelTable(name="school", table="schools",),
        migrations.AlterModelTable(name="staffevaluation", table="staff_evaluations",),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom_name",
                    models.CharField(help_text="Classroom name", max_length=100),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this classroom",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="manager.academicyear",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        help_text="Grade level for this classroom",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="manager.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School this classroom belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="manager.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
                "db_table": "class_rooms",
                "ordering": ["academic_year", "grade", "classroom_name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(help_text="Course code", max_length=50),
                ),
                ("name", models.CharField(help_text="Course name", max_length=150)),
                (
                    "grade",
                    models.ForeignKey(
                        help_text="Grade level for this course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="manager.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School offering this course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="manager.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "ordering": ["course_code", "name"],
            },
        ),
        migrations.DeleteModel(name="SystemConfiguration",),
        migrations.DeleteModel(name="WorkStream",),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "classroom_name"),
                name="unique_school_year_classroom",
            ),
        ),
    ]
