# Generated by Django 4.2.24 on 2025-12-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
        ("manager", "0002_secretary_remove_workstream_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Homeroom teacher for this classroom",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classrooms",
                to="teacher.teacher",
            ),
        ),
    ]
