# Generated by Django 4.2.24 on 2026-01-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_staffevaluation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffevaluation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="staffevaluation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
