# Generated by Django 4.2.24 on 2026-01-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_classroom_homeroom_teacher"),
    ]

    operations = [
        migrations.DeleteModel(name="Secretary",),
    ]
